---
title: "parker_file"
author: "Parker Johnson"
date: "2022-11-16"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(runjags)
library(tidyverse)
library(bayesplot)
library(coda)
library(ProbBayes)
set.seed(987654321)
```

## R Markdown


```{r}
sports <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-03-29/sports.csv')

testing <- sports %>%
  filter(str_detect(classification_name, "NCAA") == TRUE & year == 2019 & 
           is.na(rev_men) == FALSE & is.na(rev_women) == FALSE) %>%
  mutate(Division = str_extract(classification_name, "Division I{1,3}"), 
         ratio_partic_men = partic_men / partic_women) %>%
  select(institution_name, city_txt, state_cd, Division, ef_total_count, 
         partic_men, partic_women, ratio_partic_men, rev_men, rev_women, 
         total_rev_menwomen, sports) %>%
  mutate(div1_indicator = as.numeric(Division == "Division I"), 
         div2_indicator = as.numeric(Division == "Division II"))

#sum(is.na(testing$partic_coed_women) == FALSE) It's 3, same for men. Unimportant
```

```{r}
sports2019 <- sports %>% 
  filter(
    year == 2019 & 
    str_detect(classification_name, "NCAA") == TRUE & 
    sum_partic_men > 0 & sum_partic_women > 0) %>% 
  mutate(division = str_extract(classification_name, "NCAA Division I{1,3}"), 
         gender_ratio = sum_partic_men / sum_partic_women,
         division1 = as.numeric(division == "NCAA Division I"),
         division2 = as.numeric(division == "NCAA Division II"),
         school_code = as.numeric(as_factor(institution_name))) %>%
  drop_na(total_rev_menwomen)
```


```{r}
model_string <-"model {
## sampling
for (i in 1:N){
   y[i] ~ dnorm(mu[i], resid_precision)
   mu[i] <- beta0 + 
            beta1 * division1[i] + 
            beta2 * division2[i] + 
            beta3 * gender_ratio[i] + 
            u[school[i]]
}
## random effects
for (j in 1:J){
   u[j] ~ dnorm(0, school_precision)
}
## fixed effects
beta0 ~ dnorm(0, 0.01)
beta1 ~ dnorm(0, 0.01)
beta2 ~ dnorm(0, 0.01)
beta3 ~ dnorm(0, 0.01)
## variance components
resid_precision ~ dunif(0, 100)
resid_variance <- sqrt(pow(resid_precision, -1))
school_precision ~ dunif(0, 100)
school_variance <- sqrt(pow(school_precision, -1))
}
"

the_data <- list(y = log(sports2019$total_rev_menwomen), 
                 school = sports2019$school_code, 
                 division1 = sports2019$division1,
                 division2 = sports2019$division2,
                 gender_ratio = sports2019$gender_ratio,
                 N = nrow(sports2019), 
                 J = length(unique(sports2019$institution_name))
)

initsfunction <- function(chain){
  .RNG.seed <- c(123809474, 234098, 82357)[chain]
  .RNG.name <- c("base::Super-Duper",
                 "base::Wichmann-Hill",
                 "base::Mersenne-Twister")[chain]
  return(list(.RNG.seed=.RNG.seed,
              .RNG.name=.RNG.name))
}
```

``` {r}
#With 1 chain, this took 11 minutes to run on a lab computer on maize
posterior <- run.jags(
  model_string,
  n.chains = 1,
  data = the_data,
  monitor = c("beta0", "beta1", "beta2", "beta3", "u", "resid_variance", "school_variance"),
  adapt = 1000,
  burnin = 5000,
  sample = 5000,
  inits = initsfunction,
  silent.jags = TRUE, 
  thin = 20
)
```

```{r}
#All diagnostics look good
mcmc_trace(posterior$mcmc, pars = c("beta0", "beta1", "beta2", "beta3", "resid_variance", "school_variance"))
mcmc_acf(posterior$mcmc, pars = c("beta0", "beta1", "beta2", "beta3", "resid_variance", "school_variance"))
effectiveSize(posterior$mcmc)
effectiveSize(posterior$mcmc[[1]][,"resid_variance"])
effectiveSize(posterior$mcmc[[1]][,"school_variance"])
```

```{r}
geweke.diag(posterior$mcmc[[1]])
geweke.diag(posterior$mcmc[[1]][,"resid_variance"])
geweke.diag(posterior$mcmc[[1]][,"school_variance"])
```




```{r}
#I'm not sure if this means anything, but institution_summary is a data frame of 
#the random effect for each school.

df_summary <- data.frame(unclass(summary(posterior$mcmc))) #Data frame of summary
df_summary2 <- df_summary[-c(1, 2, 3, 4, 1068, 1069), ] %>% #Data frame of just institutions
  select(-c(statistics.Naive.SE, statistics.Time.series.SE, start, end, thin, nchain)) #Removing unnecessary columns

institutions <- data.frame(institution = unique(sports2019$institution_name))

institution_summary <- df_summary2 %>%
  mutate(instution = institutions$institution) #Adding names of institutions

#Reordering and renaming the data frame
institution_summary <- institution_summary[, c(8, 1, 2, 3, 4, 5, 6, 7)] %>%
  rename(Mean = statistics.Mean, SD = statistics.SD, 
         `2.5th quantile` = quantiles.2.5., `25th quantile` = quantiles.25., 
         `50th quantile` = quantiles.50., `75th quantile` = quantiles.75., 
         `97.5th quantile` = quantiles.97.5.)
```


```{r}
#This didn't work
post_df <- as.data.frame(posterior$mcmc[[1]])

postpred_sim <- function(j){
  mu_j = rnorm(nrow(post_df), post_df$mu, post_df$tau)      # generate mu_j
  y_pred = rnorm(nrow(post_df), mu_j, post_df$sigma)
}
#set.seed(597)
ypred <- t(sapply(1:5000, postpred_sim)) #Doing this 5000 times
postpred_max <- apply(ypred, 1, max)
#Finding the maximum value for each replicated dataset
```


```{r}
post_draws <- tidy_draws(posterior)

mu_link <- function(division1) {
  post_draws[["beta0"]] + post_draws[["beta1"]] * division1 + 
    post_draws[["beta2"]] * division2 + post_draws[["beta3"]] * gender_ratio + school
}

#Here's where I would get confused here
mu_draws <- sapply(olympic_butterfly_women$Year - 1964, mu_link)
S <- nrow(post_draws)
y_draws <- apply(mu_draws, 2, function(x) rnorm(S, x, post_draws[["sigma"]]))
y_means <- colMeans(y_draws)
y_pis <- apply(y_draws, 2, quantile, probs = c(0.05, 0.95))

post_pred_data <- data.frame(
  y = olympic_butterfly_women$Time, # original y
  y_pred = y_means,                # avg. predicted response
  y_lo = y_pis[1,],                # lower bound of predicted response
  y_hi = y_pis[2,]                 # upper bound of predicted response
)
```









